# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'balance_detail.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_balance_detailDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(753, 356)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 290, 491, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deletePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout_3.addWidget(self.deletePushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.printPushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.printPushButton.setFont(font)
        self.printPushButton.setObjectName("printPushButton")
        self.horizontalLayout_3.addWidget(self.printPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.savePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_3.addWidget(self.savePushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cancelPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.horizontalLayout_3.setStretch(1, 6)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(130, 40, 512, 201))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.balanceNoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.balanceNoLineEdit.setMaxLength(15)
        self.balanceNoLineEdit.setReadOnly(True)
        self.balanceNoLineEdit.setObjectName("balanceNoLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.balanceNoLineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.totalWeightLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.totalWeightLineEdit.setReadOnly(True)
        self.totalWeightLineEdit.setObjectName("totalWeightLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.totalWeightLineEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.actualWeightLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.actualWeightLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.actualWeightLineEdit.setReadOnly(True)
        self.actualWeightLineEdit.setObjectName("actualWeightLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.actualWeightLineEdit)
        self.totalWeighttimeLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.totalWeighttimeLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.totalWeighttimeLineEdit.setReadOnly(True)
        self.totalWeighttimeLineEdit.setObjectName("totalWeighttimeLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.totalWeighttimeLineEdit)
        self.receiverNameLineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.receiverNameLineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.receiverNameLineEdit_3.setObjectName("receiverNameLineEdit_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.receiverNameLineEdit_3)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.operatorLineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.operatorLineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.operatorLineEdit_4.setReadOnly(True)
        self.operatorLineEdit_4.setObjectName("operatorLineEdit_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.operatorLineEdit_4)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.carNoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.carNoLineEdit.setMaxLength(15)
        self.carNoLineEdit.setReadOnly(True)
        self.carNoLineEdit.setObjectName("carNoLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carNoLineEdit)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.leatherWeightLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.leatherWeightLineEdit.setReadOnly(True)
        self.leatherWeightLineEdit.setObjectName("leatherWeightLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leatherWeightLineEdit)
        self.leatherWeighttimeLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.leatherWeighttimeLineEdit.setObjectName("leatherWeighttimeLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leatherWeighttimeLineEdit)
        self.cargoNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.cargoNameLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cargoNameLineEdit.setDragEnabled(True)
        self.cargoNameLineEdit.setReadOnly(True)
        self.cargoNameLineEdit.setPlaceholderText("")
        self.cargoNameLineEdit.setClearButtonEnabled(False)
        self.cargoNameLineEdit.setObjectName("cargoNameLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cargoNameLineEdit)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.supplyNameLineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.supplyNameLineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.supplyNameLineEdit_2.setObjectName("supplyNameLineEdit_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.supplyNameLineEdit_2)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.deletePushButton.setText(_translate("Dialog", "删除"))
        self.printPushButton.setText(_translate("Dialog", "打印"))
        self.savePushButton.setText(_translate("Dialog", "保存"))
        self.cancelPushButton.setText(_translate("Dialog", "取消"))
        self.groupBox.setTitle(_translate("Dialog", "供货单位"))
        self.label_5.setText(_translate("Dialog", "磅  单 号："))
        self.label_8.setText(_translate("Dialog", "毛      重："))
        self.label_7.setText(_translate("Dialog", "净      重："))
        self.label_16.setText(_translate("Dialog", "操  作 员："))
        self.label_12.setText(_translate("Dialog", "收货单位："))
        self.label_15.setText(_translate("Dialog", "毛重时间："))
        self.label_10.setText(_translate("Dialog", "车      号："))
        self.label_9.setText(_translate("Dialog", "皮      重："))
        self.label_14.setText(_translate("Dialog", "皮重时间："))
        self.label_13.setText(_translate("Dialog", "货物名称："))
        self.label_11.setText(_translate("Dialog", "供货单位："))

