# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'balance_detail.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_balance_detailDialog(object):
    def setupUi(self, balance_detailDialog):
        balance_detailDialog.setObjectName("balance_detailDialog")
        balance_detailDialog.resize(1166, 764)
        self.layoutWidget = QtWidgets.QWidget(balance_detailDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(320, 290, 491, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deletePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout_3.addWidget(self.deletePushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.printPushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.printPushButton.setFont(font)
        self.printPushButton.setObjectName("printPushButton")
        self.horizontalLayout_3.addWidget(self.printPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.savePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_3.addWidget(self.savePushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cancelPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.horizontalLayout_3.setStretch(1, 6)
        self.groupBox = QtWidgets.QGroupBox(balance_detailDialog)
        self.groupBox.setGeometry(QtCore.QRect(290, 40, 512, 231))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.balanceNoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.balanceNoLineEdit.setMaxLength(15)
        self.balanceNoLineEdit.setReadOnly(True)
        self.balanceNoLineEdit.setObjectName("balanceNoLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.balanceNoLineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.totalWeightLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.totalWeightLineEdit.setReadOnly(True)
        self.totalWeightLineEdit.setObjectName("totalWeightLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.totalWeightLineEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.actualWeightLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.actualWeightLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.actualWeightLineEdit.setReadOnly(True)
        self.actualWeightLineEdit.setObjectName("actualWeightLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.actualWeightLineEdit)
        self.totalWeighttimeLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.totalWeighttimeLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.totalWeighttimeLineEdit.setReadOnly(True)
        self.totalWeighttimeLineEdit.setObjectName("totalWeighttimeLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.totalWeighttimeLineEdit)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.operatorLineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.operatorLineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.operatorLineEdit_4.setReadOnly(True)
        self.operatorLineEdit_4.setObjectName("operatorLineEdit_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.operatorLineEdit_4)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.receiverComboBox = QtWidgets.QComboBox(self.groupBox)
        self.receiverComboBox.setEditable(True)
        self.receiverComboBox.setObjectName("receiverComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.receiverComboBox)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.SettlementLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SettlementLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SettlementLineEdit.setReadOnly(True)
        self.SettlementLineEdit.setObjectName("SettlementLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SettlementLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.carNoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.carNoLineEdit.setMaxLength(15)
        self.carNoLineEdit.setReadOnly(True)
        self.carNoLineEdit.setObjectName("carNoLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carNoLineEdit)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.leatherWeightLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.leatherWeightLineEdit.setReadOnly(True)
        self.leatherWeightLineEdit.setObjectName("leatherWeightLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leatherWeightLineEdit)
        self.leatherWeighttimeLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.leatherWeighttimeLineEdit.setObjectName("leatherWeighttimeLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leatherWeighttimeLineEdit)
        self.cargoNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.cargoNameLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cargoNameLineEdit.setDragEnabled(True)
        self.cargoNameLineEdit.setReadOnly(True)
        self.cargoNameLineEdit.setPlaceholderText("")
        self.cargoNameLineEdit.setClearButtonEnabled(False)
        self.cargoNameLineEdit.setObjectName("cargoNameLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cargoNameLineEdit)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.supplierComboBox = QtWidgets.QComboBox(self.groupBox)
        self.supplierComboBox.setEditable(True)
        self.supplierComboBox.setObjectName("supplierComboBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.supplierComboBox)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.extraWeightLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.extraWeightLineEdit.setReadOnly(True)
        self.extraWeightLineEdit.setObjectName("extraWeightLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.extraWeightLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(balance_detailDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 340, 550, 420))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_1 = MyQGraphicsView(self.groupBox_2)
        self.graphicsView_1.setGeometry(QtCore.QRect(0, 20, 256, 171))
        self.graphicsView_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.graphicsView_2 = MyQGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(290, 20, 256, 171))
        self.graphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = MyQGraphicsView(self.groupBox_2)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 230, 256, 171))
        self.graphicsView_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = MyQGraphicsView(self.groupBox_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(290, 230, 256, 171))
        self.graphicsView_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.groupBox_3 = QtWidgets.QGroupBox(balance_detailDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 340, 550, 420))
        self.groupBox_3.setTabletTracking(False)
        self.groupBox_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.graphicsView_5 = MyQGraphicsView(self.groupBox_3)
        self.graphicsView_5.setGeometry(QtCore.QRect(0, 20, 256, 171))
        self.graphicsView_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = MyQGraphicsView(self.groupBox_3)
        self.graphicsView_6.setGeometry(QtCore.QRect(290, 20, 256, 171))
        self.graphicsView_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_8 = MyQGraphicsView(self.groupBox_3)
        self.graphicsView_8.setGeometry(QtCore.QRect(290, 230, 256, 171))
        self.graphicsView_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_7 = MyQGraphicsView(self.groupBox_3)
        self.graphicsView_7.setGeometry(QtCore.QRect(0, 230, 256, 171))
        self.graphicsView_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_7.setObjectName("graphicsView_7")

        self.retranslateUi(balance_detailDialog)
        QtCore.QMetaObject.connectSlotsByName(balance_detailDialog)

    def retranslateUi(self, balance_detailDialog):
        _translate = QtCore.QCoreApplication.translate
        balance_detailDialog.setWindowTitle(_translate("balance_detailDialog", "数据展示"))
        self.deletePushButton.setText(_translate("balance_detailDialog", "删除"))
        self.printPushButton.setText(_translate("balance_detailDialog", "打印"))
        self.savePushButton.setText(_translate("balance_detailDialog", "保存"))
        self.cancelPushButton.setText(_translate("balance_detailDialog", "取消"))
        self.groupBox.setTitle(_translate("balance_detailDialog", "供货单位"))
        self.label_5.setText(_translate("balance_detailDialog", "磅  单 号："))
        self.label_8.setText(_translate("balance_detailDialog", "毛      重："))
        self.label_7.setText(_translate("balance_detailDialog", "净      重："))
        self.label_16.setText(_translate("balance_detailDialog", "操  作 员："))
        self.label_12.setText(_translate("balance_detailDialog", "收货单位："))
        self.label_15.setText(_translate("balance_detailDialog", "毛重时间："))
        self.label_18.setText(_translate("balance_detailDialog", "结算重量："))
        self.label_10.setText(_translate("balance_detailDialog", "车      号："))
        self.label_9.setText(_translate("balance_detailDialog", "皮      重："))
        self.label_14.setText(_translate("balance_detailDialog", "皮重时间："))
        self.label_13.setText(_translate("balance_detailDialog", "货物名称："))
        self.label_11.setText(_translate("balance_detailDialog", "供货单位："))
        self.label_17.setText(_translate("balance_detailDialog", "另      扣："))
        self.groupBox_2.setTitle(_translate("balance_detailDialog", "第一次称重"))
        self.groupBox_3.setTitle(_translate("balance_detailDialog", "第二次称重"))

from ui.my_qgraphics_view import MyQGraphicsView
