# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'balance.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(657, 684)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        mainWindow.setFont(font)
        mainWindow.setAcceptDrops(False)
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(600, 100))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.weightLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.weightLabel.setFont(font)
        self.weightLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.weightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weightLabel.setWordWrap(False)
        self.weightLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.weightLabel.setObjectName("weightLabel")
        self.horizontalLayout.addWidget(self.weightLabel)
        self.weightLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.weightLcdNumber.setEnabled(True)
        self.weightLcdNumber.setMinimumSize(QtCore.QSize(200, 60))
        self.weightLcdNumber.setMaximumSize(QtCore.QSize(500, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weightLcdNumber.setFont(font)
        self.weightLcdNumber.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.weightLcdNumber.setMouseTracking(False)
        self.weightLcdNumber.setTabletTracking(False)
        self.weightLcdNumber.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.weightLcdNumber.setAcceptDrops(False)
        self.weightLcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.weightLcdNumber.setAutoFillBackground(False)
        self.weightLcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.weightLcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.weightLcdNumber.setLineWidth(1)
        self.weightLcdNumber.setMidLineWidth(0)
        self.weightLcdNumber.setSmallDecimalPoint(True)
        self.weightLcdNumber.setDigitCount(8)
        self.weightLcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.weightLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.weightLcdNumber.setProperty("value", 12302.0)
        self.weightLcdNumber.setProperty("intValue", 12302)
        self.weightLcdNumber.setObjectName("weightLcdNumber")
        self.horizontalLayout.addWidget(self.weightLcdNumber)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.stateLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.stateLabel.setFont(font)
        self.stateLabel.setStyleSheet("color:rgb(255, 0, 0)")
        self.stateLabel.setTextFormat(QtCore.Qt.AutoText)
        self.stateLabel.setObjectName("stateLabel")
        self.horizontalLayout.addWidget(self.stateLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.balanceNoBlael = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.balanceNoBlael.setFont(font)
        self.balanceNoBlael.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.balanceNoBlael.setObjectName("balanceNoBlael")
        self.horizontalLayout_2.addWidget(self.balanceNoBlael)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pickBalanceButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pickBalanceButton.setFont(font)
        self.pickBalanceButton.setObjectName("pickBalanceButton")
        self.horizontalLayout_2.addWidget(self.pickBalanceButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(4, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.totalWeightLcdNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.totalWeightLcdNumber.setSmallDecimalPoint(True)
        self.totalWeightLcdNumber.setDigitCount(8)
        self.totalWeightLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.totalWeightLcdNumber.setProperty("intValue", 12345678)
        self.totalWeightLcdNumber.setObjectName("totalWeightLcdNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.totalWeightLcdNumber)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.leatherWeightLcdNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leatherWeightLcdNumber.setFont(font)
        self.leatherWeightLcdNumber.setSmallDecimalPoint(True)
        self.leatherWeightLcdNumber.setDigitCount(8)
        self.leatherWeightLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.leatherWeightLcdNumber.setProperty("intValue", 12345678)
        self.leatherWeightLcdNumber.setObjectName("leatherWeightLcdNumber")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leatherWeightLcdNumber)
        self.actualWeightLcdNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.actualWeightLcdNumber.setSmallDecimalPoint(True)
        self.actualWeightLcdNumber.setDigitCount(8)
        self.actualWeightLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.actualWeightLcdNumber.setProperty("intValue", 12345678)
        self.actualWeightLcdNumber.setObjectName("actualWeightLcdNumber")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.actualWeightLcdNumber)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.extraWeightSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.extraWeightSpinBox.setMaximum(99999.0)
        self.extraWeightSpinBox.setObjectName("extraWeightSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.extraWeightSpinBox)
        self.priceSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.priceSpinBox.setMaximum(99999.99)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.priceSpinBox)
        self.amountSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.amountSpinBox.setMaximum(99999.99)
        self.amountSpinBox.setObjectName("amountSpinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.amountSpinBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem10)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setIndent(0)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.CarComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.CarComboBox.setEditable(True)
        self.CarComboBox.setObjectName("CarComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CarComboBox)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setIndent(0)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.supplierComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.supplierComboBox.setEditable(True)
        self.supplierComboBox.setObjectName("supplierComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.supplierComboBox)
        self.receiverComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.receiverComboBox.setEditable(True)
        self.receiverComboBox.setObjectName("receiverComboBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.receiverComboBox)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setWordWrap(False)
        self.label_14.setIndent(0)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.goodsComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.goodsComboBox.setEditable(True)
        self.goodsComboBox.setObjectName("goodsComboBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.goodsComboBox)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setWordWrap(False)
        self.label_15.setIndent(0)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setWordWrap(False)
        self.label_16.setIndent(0)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.operatorComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.operatorComboBox.setEditable(True)
        self.operatorComboBox.setObjectName("operatorComboBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.operatorComboBox)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem18)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.printPushButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.printPushButton.setFont(font)
        self.printPushButton.setObjectName("printPushButton")
        self.horizontalLayout_4.addWidget(self.printPushButton)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem20)
        self.savePushButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.savePushButton.setFont(font)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_4.addWidget(self.savePushButton)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem21)
        self.rmLeatherPushButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rmLeatherPushButton.setFont(font)
        self.rmLeatherPushButton.setObjectName("rmLeatherPushButton")
        self.horizontalLayout_4.addWidget(self.rmLeatherPushButton)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem22)
        self.clearPushButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearPushButton.setFont(font)
        self.clearPushButton.setObjectName("clearPushButton")
        self.horizontalLayout_4.addWidget(self.clearPushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(4, 6)
        self.verticalLayout_4.setStretch(6, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setEnabled(True)
        self.tableView.setAutoFillBackground(False)
        self.tableView.setStyleSheet("QTableView QHeaderView::section { background-color:#dadada}")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout_5.addWidget(self.tableView)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 2)
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 657, 23))
        self.menuBar.setObjectName("menuBar")
        self.qmenuSystemSetup = QtWidgets.QMenu(self.menuBar)
        self.qmenuSystemSetup.setObjectName("qmenuSystemSetup")
        self.qmenuBasicInfoSetup = QtWidgets.QMenu(self.menuBar)
        self.qmenuBasicInfoSetup.setObjectName("qmenuBasicInfoSetup")
        self.qmenuQuery = QtWidgets.QMenu(self.menuBar)
        self.qmenuQuery.setObjectName("qmenuQuery")
        self.qmenuHelp = QtWidgets.QMenu(self.menuBar)
        self.qmenuHelp.setObjectName("qmenuHelp")
        mainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.actionBalanceFormSetup = QtWidgets.QAction(mainWindow)
        self.actionBalanceFormSetup.setObjectName("actionBalanceFormSetup")
        self.actionParameterSetup = QtWidgets.QAction(mainWindow)
        self.actionParameterSetup.setObjectName("actionParameterSetup")
        self.actionUserPermission = QtWidgets.QAction(mainWindow)
        self.actionUserPermission.setObjectName("actionUserPermission")
        self.actionSystemParameterSetup = QtWidgets.QAction(mainWindow)
        self.actionSystemParameterSetup.setObjectName("actionSystemParameterSetup")
        self.actionCarInfo = QtWidgets.QAction(mainWindow)
        self.actionCarInfo.setObjectName("actionCarInfo")
        self.actionSupplier = QtWidgets.QAction(mainWindow)
        self.actionSupplier.setObjectName("actionSupplier")
        self.actionReceiving = QtWidgets.QAction(mainWindow)
        self.actionReceiving.setObjectName("actionReceiving")
        self.actionGoodsName = QtWidgets.QAction(mainWindow)
        self.actionGoodsName.setObjectName("actionGoodsName")
        self.actionBalanceQuery = QtWidgets.QAction(mainWindow)
        self.actionBalanceQuery.setObjectName("actionBalanceQuery")
        self.actionHelp = QtWidgets.QAction(mainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.qmenuSystemSetup.addAction(self.actionBalanceFormSetup)
        self.qmenuSystemSetup.addAction(self.actionParameterSetup)
        self.qmenuSystemSetup.addAction(self.actionUserPermission)
        self.qmenuSystemSetup.addAction(self.actionSystemParameterSetup)
        self.qmenuBasicInfoSetup.addAction(self.actionCarInfo)
        self.qmenuBasicInfoSetup.addAction(self.actionSupplier)
        self.qmenuBasicInfoSetup.addAction(self.actionReceiving)
        self.qmenuBasicInfoSetup.addAction(self.actionGoodsName)
        self.qmenuQuery.addAction(self.actionBalanceQuery)
        self.qmenuHelp.addAction(self.actionHelp)
        self.qmenuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.qmenuSystemSetup.menuAction())
        self.menuBar.addAction(self.qmenuBasicInfoSetup.menuAction())
        self.menuBar.addAction(self.qmenuQuery.menuAction())
        self.menuBar.addAction(self.qmenuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "牛逼的称重系统"))
        self.weightLabel.setText(_translate("mainWindow", "重 量："))
        self.stateLabel.setText(_translate("mainWindow", "读取中……"))
        self.groupBox_2.setTitle(_translate("mainWindow", "详细信息"))
        self.label_7.setText(_translate("mainWindow", "磅单号:"))
        self.balanceNoBlael.setText(_translate("mainWindow", "12345678945645512"))
        self.pickBalanceButton.setText(_translate("mainWindow", "取重量"))
        self.label.setText(_translate("mainWindow", "毛 重"))
        self.label_2.setText(_translate("mainWindow", "皮 重"))
        self.label_3.setText(_translate("mainWindow", "净 重"))
        self.label_4.setText(_translate("mainWindow", "另 扣"))
        self.label_6.setText(_translate("mainWindow", "单 价"))
        self.label_5.setText(_translate("mainWindow", "金 额"))
        self.label_8.setText(_translate("mainWindow", "车      号"))
        self.label_11.setText(_translate("mainWindow", "供货单位"))
        self.label_14.setText(_translate("mainWindow", "收货单位"))
        self.label_15.setText(_translate("mainWindow", "货物名称"))
        self.label_16.setText(_translate("mainWindow", " 操 作 员"))
        self.printPushButton.setText(_translate("mainWindow", "打    印"))
        self.savePushButton.setText(_translate("mainWindow", "保    存"))
        self.rmLeatherPushButton.setText(_translate("mainWindow", "去    皮"))
        self.clearPushButton.setText(_translate("mainWindow", "清    除"))
        self.qmenuSystemSetup.setTitle(_translate("mainWindow", "系统设置"))
        self.qmenuBasicInfoSetup.setTitle(_translate("mainWindow", "基本信息设置"))
        self.qmenuQuery.setTitle(_translate("mainWindow", "查询"))
        self.qmenuHelp.setTitle(_translate("mainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionBalanceFormSetup.setText(_translate("mainWindow", "磅单设置"))
        self.actionParameterSetup.setText(_translate("mainWindow", "参数设置"))
        self.actionUserPermission.setText(_translate("mainWindow", "用户和权限管理"))
        self.actionSystemParameterSetup.setText(_translate("mainWindow", "系统参数设置"))
        self.actionCarInfo.setText(_translate("mainWindow", "车辆设置"))
        self.actionSupplier.setText(_translate("mainWindow", "供货单位"))
        self.actionReceiving.setText(_translate("mainWindow", "收货单位"))
        self.actionGoodsName.setText(_translate("mainWindow", "货物名称"))
        self.actionBalanceQuery.setText(_translate("mainWindow", "程中查询"))
        self.actionHelp.setText(_translate("mainWindow", "帮助信息"))
        self.actionAbout.setText(_translate("mainWindow", "关于"))

