# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_no_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(420, 200)
        DockWidget.setMinimumSize(QtCore.QSize(420, 200))
        DockWidget.setMaximumSize(QtCore.QSize(420, 200))
        DockWidget.setFloating(True)
        DockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        DockWidget.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 160, 401, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_84 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_84.setFont(font)
        self.pushButton_84.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_84.setObjectName("pushButton_84")
        self.horizontalLayout.addWidget(self.pushButton_84)
        self.pushButton_79 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_79.setFont(font)
        self.pushButton_79.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_79.setObjectName("pushButton_79")
        self.horizontalLayout.addWidget(self.pushButton_79)
        self.pushButton_63 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_63.setFont(font)
        self.pushButton_63.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_63.setObjectName("pushButton_63")
        self.horizontalLayout.addWidget(self.pushButton_63)
        self.pushButton_61 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_61.setObjectName("pushButton_61")
        self.horizontalLayout.addWidget(self.pushButton_61)
        self.pushButton_60 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_60.setObjectName("pushButton_60")
        self.horizontalLayout.addWidget(self.pushButton_60)
        self.pushButton_71 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_71.setFont(font)
        self.pushButton_71.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_71.setObjectName("pushButton_71")
        self.horizontalLayout.addWidget(self.pushButton_71)
        self.pushButton_57 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_57.setObjectName("pushButton_57")
        self.horizontalLayout.addWidget(self.pushButton_57)
        self.pushButton_72 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_72.setFont(font)
        self.pushButton_72.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_72.setObjectName("pushButton_72")
        self.horizontalLayout.addWidget(self.pushButton_72)
        self.pushButton_77 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_77.setFont(font)
        self.pushButton_77.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_77.setObjectName("pushButton_77")
        self.horizontalLayout.addWidget(self.pushButton_77)
        self.pushButton_82 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_82.setFont(font)
        self.pushButton_82.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_82.setObjectName("pushButton_82")
        self.horizontalLayout.addWidget(self.pushButton_82)
        self.pushButton_73 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_73.setFont(font)
        self.pushButton_73.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_73.setObjectName("pushButton_73")
        self.horizontalLayout.addWidget(self.pushButton_73)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_78 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_78.setFont(font)
        self.pushButton_78.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_78.setObjectName("pushButton_78")
        self.horizontalLayout.addWidget(self.pushButton_78)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(6, 1)
        self.horizontalLayout.setStretch(7, 1)
        self.horizontalLayout.setStretch(8, 1)
        self.horizontalLayout.setStretch(9, 1)
        self.horizontalLayout.setStretch(10, 1)
        self.horizontalLayout.setStretch(11, 1)
        self.horizontalLayout.setStretch(12, 2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.dockWidgetContents)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 398, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_62 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_62.setFont(font)
        self.pushButton_62.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_62.setObjectName("pushButton_62")
        self.gridLayout.addWidget(self.pushButton_62, 2, 7, 1, 1)
        self.pushButton_67 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_67.setFont(font)
        self.pushButton_67.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_67.setObjectName("pushButton_67")
        self.gridLayout.addWidget(self.pushButton_67, 2, 8, 1, 1)
        self.pushButton_80 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_80.setFont(font)
        self.pushButton_80.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_80.setObjectName("pushButton_80")
        self.gridLayout.addWidget(self.pushButton_80, 2, 9, 1, 1)
        self.pushButton_81 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_81.setFont(font)
        self.pushButton_81.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_81.setObjectName("pushButton_81")
        self.gridLayout.addWidget(self.pushButton_81, 2, 0, 1, 1)
        self.pushButton_85 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_85.setFont(font)
        self.pushButton_85.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_85.setObjectName("pushButton_85")
        self.gridLayout.addWidget(self.pushButton_85, 2, 1, 1, 1)
        self.pushButton_86 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_86.setFont(font)
        self.pushButton_86.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_86.setObjectName("pushButton_86")
        self.gridLayout.addWidget(self.pushButton_86, 2, 3, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout.addWidget(self.pushButton_34, 2, 4, 1, 1)
        self.pushButton_87 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_87.setFont(font)
        self.pushButton_87.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_87.setObjectName("pushButton_87")
        self.gridLayout.addWidget(self.pushButton_87, 2, 12, 1, 1)
        self.pushButton_88 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_88.setFont(font)
        self.pushButton_88.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_88.setObjectName("pushButton_88")
        self.gridLayout.addWidget(self.pushButton_88, 2, 6, 1, 1)
        self.pushButton_89 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_89.setFont(font)
        self.pushButton_89.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_89.setObjectName("pushButton_89")
        self.gridLayout.addWidget(self.pushButton_89, 2, 11, 1, 1)
        self.pushButton_90 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_90.setFont(font)
        self.pushButton_90.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_90.setObjectName("pushButton_90")
        self.gridLayout.addWidget(self.pushButton_90, 2, 2, 1, 1)
        self.pushButton_91 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_91.setFont(font)
        self.pushButton_91.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_91.setObjectName("pushButton_91")
        self.gridLayout.addWidget(self.pushButton_91, 2, 10, 1, 1)
        self.pushButton_92 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_92.setFont(font)
        self.pushButton_92.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_92.setObjectName("pushButton_92")
        self.gridLayout.addWidget(self.pushButton_92, 2, 5, 1, 1)
        self.pushButton_93 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_93.setFont(font)
        self.pushButton_93.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_93.setObjectName("pushButton_93")
        self.gridLayout.addWidget(self.pushButton_93, 4, 8, 1, 1)
        self.pushButton_94 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_94.setFont(font)
        self.pushButton_94.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_94.setObjectName("pushButton_94")
        self.gridLayout.addWidget(self.pushButton_94, 4, 11, 1, 1)
        self.pushButton_95 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_95.setFont(font)
        self.pushButton_95.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_95.setObjectName("pushButton_95")
        self.gridLayout.addWidget(self.pushButton_95, 4, 12, 1, 1)
        self.pushButton_96 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_96.setFont(font)
        self.pushButton_96.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_96.setObjectName("pushButton_96")
        self.gridLayout.addWidget(self.pushButton_96, 4, 10, 1, 1)
        self.pushButton_97 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_97.setFont(font)
        self.pushButton_97.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_97.setObjectName("pushButton_97")
        self.gridLayout.addWidget(self.pushButton_97, 4, 13, 1, 1)
        self.pushButton_98 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_98.setFont(font)
        self.pushButton_98.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_98.setObjectName("pushButton_98")
        self.gridLayout.addWidget(self.pushButton_98, 4, 4, 1, 1)
        self.pushButton_99 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_99.setFont(font)
        self.pushButton_99.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_99.setObjectName("pushButton_99")
        self.gridLayout.addWidget(self.pushButton_99, 4, 9, 1, 1)
        self.pushButton_100 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_100.setFont(font)
        self.pushButton_100.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_100.setObjectName("pushButton_100")
        self.gridLayout.addWidget(self.pushButton_100, 4, 2, 1, 1)
        self.pushButton_101 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_101.setFont(font)
        self.pushButton_101.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_101.setObjectName("pushButton_101")
        self.gridLayout.addWidget(self.pushButton_101, 4, 1, 1, 1)
        self.pushButton_102 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_102.setFont(font)
        self.pushButton_102.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_102.setObjectName("pushButton_102")
        self.gridLayout.addWidget(self.pushButton_102, 4, 5, 1, 1)
        self.pushButton_103 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_103.setFont(font)
        self.pushButton_103.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_103.setObjectName("pushButton_103")
        self.gridLayout.addWidget(self.pushButton_103, 4, 3, 1, 1)
        self.pushButton_104 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_104.setFont(font)
        self.pushButton_104.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_104.setObjectName("pushButton_104")
        self.gridLayout.addWidget(self.pushButton_104, 4, 6, 1, 1)
        self.pushButton_105 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_105.setFont(font)
        self.pushButton_105.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_105.setObjectName("pushButton_105")
        self.gridLayout.addWidget(self.pushButton_105, 4, 7, 1, 1)
        self.pushButton_106 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_106.setFont(font)
        self.pushButton_106.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_106.setObjectName("pushButton_106")
        self.gridLayout.addWidget(self.pushButton_106, 4, 0, 1, 1)
        self.pushButton_107 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_107.setFont(font)
        self.pushButton_107.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_107.setObjectName("pushButton_107")
        self.gridLayout.addWidget(self.pushButton_107, 5, 1, 1, 1)
        self.pushButton_108 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_108.setFont(font)
        self.pushButton_108.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_108.setObjectName("pushButton_108")
        self.gridLayout.addWidget(self.pushButton_108, 5, 0, 1, 1)
        self.pushButton_109 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_109.setFont(font)
        self.pushButton_109.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_109.setObjectName("pushButton_109")
        self.gridLayout.addWidget(self.pushButton_109, 5, 3, 1, 1)
        self.pushButton_110 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_110.setFont(font)
        self.pushButton_110.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_110.setObjectName("pushButton_110")
        self.gridLayout.addWidget(self.pushButton_110, 5, 4, 1, 1)
        self.pushButton_111 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_111.setFont(font)
        self.pushButton_111.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_111.setObjectName("pushButton_111")
        self.gridLayout.addWidget(self.pushButton_111, 5, 2, 1, 1)
        self.pushButton_112 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_112.setFont(font)
        self.pushButton_112.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_112.setObjectName("pushButton_112")
        self.gridLayout.addWidget(self.pushButton_112, 5, 5, 1, 1)
        self.pushButton_113 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_113.setFont(font)
        self.pushButton_113.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_113.setObjectName("pushButton_113")
        self.gridLayout.addWidget(self.pushButton_113, 5, 6, 1, 1)
        self.pushButton_114 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_114.setFont(font)
        self.pushButton_114.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_114.setObjectName("pushButton_114")
        self.gridLayout.addWidget(self.pushButton_114, 5, 7, 1, 1)
        self.pushButton_115 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_115.setFont(font)
        self.pushButton_115.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_115.setObjectName("pushButton_115")
        self.gridLayout.addWidget(self.pushButton_115, 5, 10, 1, 1)
        self.pushButton_116 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_116.setFont(font)
        self.pushButton_116.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_116.setObjectName("pushButton_116")
        self.gridLayout.addWidget(self.pushButton_116, 5, 11, 1, 1)
        self.pushButton_117 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_117.setFont(font)
        self.pushButton_117.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_117.setObjectName("pushButton_117")
        self.gridLayout.addWidget(self.pushButton_117, 5, 8, 1, 1)
        self.pushButton_118 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_118.setFont(font)
        self.pushButton_118.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_118.setObjectName("pushButton_118")
        self.gridLayout.addWidget(self.pushButton_118, 5, 9, 1, 1)
        self.pushButton_119 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_119.setFont(font)
        self.pushButton_119.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_119.setObjectName("pushButton_119")
        self.gridLayout.addWidget(self.pushButton_119, 0, 0, 1, 1)
        self.pushButton_120 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_120.setFont(font)
        self.pushButton_120.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_120.setObjectName("pushButton_120")
        self.gridLayout.addWidget(self.pushButton_120, 0, 4, 1, 1)
        self.pushButton_121 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_121.setFont(font)
        self.pushButton_121.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_121.setObjectName("pushButton_121")
        self.gridLayout.addWidget(self.pushButton_121, 1, 3, 1, 1)
        self.pushButton_122 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_122.setFont(font)
        self.pushButton_122.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_122.setObjectName("pushButton_122")
        self.gridLayout.addWidget(self.pushButton_122, 0, 6, 1, 1)
        self.pushButton_123 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_123.setFont(font)
        self.pushButton_123.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_123.setObjectName("pushButton_123")
        self.gridLayout.addWidget(self.pushButton_123, 0, 12, 1, 1)
        self.pushButton_124 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_124.setFont(font)
        self.pushButton_124.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_124.setObjectName("pushButton_124")
        self.gridLayout.addWidget(self.pushButton_124, 0, 13, 1, 1)
        self.pushButton_125 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_125.setFont(font)
        self.pushButton_125.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_125.setObjectName("pushButton_125")
        self.gridLayout.addWidget(self.pushButton_125, 1, 1, 1, 1)
        self.pushButton_126 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_126.setFont(font)
        self.pushButton_126.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_126.setObjectName("pushButton_126")
        self.gridLayout.addWidget(self.pushButton_126, 0, 11, 1, 1)
        self.pushButton_127 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_127.setFont(font)
        self.pushButton_127.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_127.setObjectName("pushButton_127")
        self.gridLayout.addWidget(self.pushButton_127, 1, 2, 1, 1)
        self.pushButton_128 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_128.setFont(font)
        self.pushButton_128.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_128.setObjectName("pushButton_128")
        self.gridLayout.addWidget(self.pushButton_128, 0, 3, 1, 1)
        self.pushButton_129 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_129.setFont(font)
        self.pushButton_129.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_129.setObjectName("pushButton_129")
        self.gridLayout.addWidget(self.pushButton_129, 1, 4, 1, 1)
        self.pushButton_130 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_130.setFont(font)
        self.pushButton_130.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_130.setObjectName("pushButton_130")
        self.gridLayout.addWidget(self.pushButton_130, 1, 5, 1, 1)
        self.pushButton_131 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_131.setFont(font)
        self.pushButton_131.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_131.setObjectName("pushButton_131")
        self.gridLayout.addWidget(self.pushButton_131, 1, 6, 1, 1)
        self.pushButton_132 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_132.setFont(font)
        self.pushButton_132.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_132.setObjectName("pushButton_132")
        self.gridLayout.addWidget(self.pushButton_132, 1, 0, 1, 1)
        self.pushButton_133 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_133.setFont(font)
        self.pushButton_133.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_133.setObjectName("pushButton_133")
        self.gridLayout.addWidget(self.pushButton_133, 0, 7, 1, 1)
        self.pushButton_134 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_134.setFont(font)
        self.pushButton_134.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_134.setObjectName("pushButton_134")
        self.gridLayout.addWidget(self.pushButton_134, 1, 7, 1, 1)
        self.pushButton_135 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_135.setFont(font)
        self.pushButton_135.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_135.setObjectName("pushButton_135")
        self.gridLayout.addWidget(self.pushButton_135, 0, 2, 1, 1)
        self.pushButton_136 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_136.setFont(font)
        self.pushButton_136.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_136.setObjectName("pushButton_136")
        self.gridLayout.addWidget(self.pushButton_136, 0, 9, 1, 1)
        self.pushButton_137 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_137.setFont(font)
        self.pushButton_137.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_137.setObjectName("pushButton_137")
        self.gridLayout.addWidget(self.pushButton_137, 0, 5, 1, 1)
        self.pushButton_138 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_138.setFont(font)
        self.pushButton_138.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_138.setObjectName("pushButton_138")
        self.gridLayout.addWidget(self.pushButton_138, 0, 10, 1, 1)
        self.pushButton_139 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_139.setFont(font)
        self.pushButton_139.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_139.setObjectName("pushButton_139")
        self.gridLayout.addWidget(self.pushButton_139, 0, 8, 1, 1)
        self.pushButton_140 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_140.setFont(font)
        self.pushButton_140.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_140.setObjectName("pushButton_140")
        self.gridLayout.addWidget(self.pushButton_140, 0, 1, 1, 1)
        self.pushButton_141 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_141.setFont(font)
        self.pushButton_141.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_141.setObjectName("pushButton_141")
        self.gridLayout.addWidget(self.pushButton_141, 1, 12, 1, 1)
        self.pushButton_142 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_142.setFont(font)
        self.pushButton_142.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_142.setObjectName("pushButton_142")
        self.gridLayout.addWidget(self.pushButton_142, 1, 13, 1, 1)
        self.pushButton_143 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_143.setFont(font)
        self.pushButton_143.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_143.setObjectName("pushButton_143")
        self.gridLayout.addWidget(self.pushButton_143, 1, 8, 1, 1)
        self.pushButton_144 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_144.setFont(font)
        self.pushButton_144.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_144.setObjectName("pushButton_144")
        self.gridLayout.addWidget(self.pushButton_144, 1, 10, 1, 1)
        self.pushButton_145 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_145.setFont(font)
        self.pushButton_145.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_145.setObjectName("pushButton_145")
        self.gridLayout.addWidget(self.pushButton_145, 1, 9, 1, 1)
        self.pushButton_146 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_146.setFont(font)
        self.pushButton_146.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_146.setObjectName("pushButton_146")
        self.gridLayout.addWidget(self.pushButton_146, 1, 11, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 6, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.pushButton_84.setText(_translate("DockWidget", "0"))
        self.pushButton_79.setText(_translate("DockWidget", "1"))
        self.pushButton_63.setText(_translate("DockWidget", "2"))
        self.pushButton_61.setText(_translate("DockWidget", "3"))
        self.pushButton_60.setText(_translate("DockWidget", "4"))
        self.pushButton_71.setText(_translate("DockWidget", "5"))
        self.pushButton_57.setText(_translate("DockWidget", "6"))
        self.pushButton_72.setText(_translate("DockWidget", "7"))
        self.pushButton_77.setText(_translate("DockWidget", "8"))
        self.pushButton_82.setText(_translate("DockWidget", "9"))
        self.pushButton_73.setText(_translate("DockWidget", "-"))
        self.pushButton_78.setText(_translate("DockWidget", "确定"))
        self.pushButton_62.setText(_translate("DockWidget", "戊"))
        self.pushButton_67.setText(_translate("DockWidget", "己"))
        self.pushButton_80.setText(_translate("DockWidget", "庚"))
        self.pushButton_81.setText(_translate("DockWidget", "青"))
        self.pushButton_85.setText(_translate("DockWidget", "宁"))
        self.pushButton_86.setText(_translate("DockWidget", "甲"))
        self.pushButton_34.setText(_translate("DockWidget", "乙"))
        self.pushButton_87.setText(_translate("DockWidget", "癸"))
        self.pushButton_88.setText(_translate("DockWidget", "丁"))
        self.pushButton_89.setText(_translate("DockWidget", "壬"))
        self.pushButton_90.setText(_translate("DockWidget", "新"))
        self.pushButton_91.setText(_translate("DockWidget", "辛"))
        self.pushButton_92.setText(_translate("DockWidget", "丙"))
        self.pushButton_93.setText(_translate("DockWidget", "I"))
        self.pushButton_94.setText(_translate("DockWidget", "L"))
        self.pushButton_95.setText(_translate("DockWidget", "M"))
        self.pushButton_96.setText(_translate("DockWidget", "K"))
        self.pushButton_97.setText(_translate("DockWidget", "N"))
        self.pushButton_98.setText(_translate("DockWidget", "E"))
        self.pushButton_99.setText(_translate("DockWidget", "J"))
        self.pushButton_100.setText(_translate("DockWidget", "C"))
        self.pushButton_101.setText(_translate("DockWidget", "B"))
        self.pushButton_102.setText(_translate("DockWidget", "F"))
        self.pushButton_103.setText(_translate("DockWidget", "D"))
        self.pushButton_104.setText(_translate("DockWidget", "G"))
        self.pushButton_105.setText(_translate("DockWidget", "H"))
        self.pushButton_106.setText(_translate("DockWidget", "A"))
        self.pushButton_107.setText(_translate("DockWidget", "P"))
        self.pushButton_108.setText(_translate("DockWidget", "O"))
        self.pushButton_109.setText(_translate("DockWidget", "R"))
        self.pushButton_110.setText(_translate("DockWidget", "S"))
        self.pushButton_111.setText(_translate("DockWidget", "Q"))
        self.pushButton_112.setText(_translate("DockWidget", "T"))
        self.pushButton_113.setText(_translate("DockWidget", "U"))
        self.pushButton_114.setText(_translate("DockWidget", "V"))
        self.pushButton_115.setText(_translate("DockWidget", "Y"))
        self.pushButton_116.setText(_translate("DockWidget", "Z"))
        self.pushButton_117.setText(_translate("DockWidget", "W"))
        self.pushButton_118.setText(_translate("DockWidget", "X"))
        self.pushButton_119.setText(_translate("DockWidget", "京"))
        self.pushButton_120.setText(_translate("DockWidget", "蒙"))
        self.pushButton_121.setText(_translate("DockWidget", "湘"))
        self.pushButton_122.setText(_translate("DockWidget", "吉"))
        self.pushButton_123.setText(_translate("DockWidget", "闽"))
        self.pushButton_124.setText(_translate("DockWidget", "赣"))
        self.pushButton_125.setText(_translate("DockWidget", "豫"))
        self.pushButton_126.setText(_translate("DockWidget", "皖"))
        self.pushButton_127.setText(_translate("DockWidget", "鄂"))
        self.pushButton_128.setText(_translate("DockWidget", "晋"))
        self.pushButton_129.setText(_translate("DockWidget", "粤"))
        self.pushButton_130.setText(_translate("DockWidget", "桂"))
        self.pushButton_131.setText(_translate("DockWidget", "琼"))
        self.pushButton_132.setText(_translate("DockWidget", "鲁"))
        self.pushButton_133.setText(_translate("DockWidget", "黑"))
        self.pushButton_134.setText(_translate("DockWidget", "渝"))
        self.pushButton_135.setText(_translate("DockWidget", "冀"))
        self.pushButton_136.setText(_translate("DockWidget", "苏"))
        self.pushButton_137.setText(_translate("DockWidget", "辽"))
        self.pushButton_138.setText(_translate("DockWidget", "浙"))
        self.pushButton_139.setText(_translate("DockWidget", "沪"))
        self.pushButton_140.setText(_translate("DockWidget", "津"))
        self.pushButton_141.setText(_translate("DockWidget", "陕"))
        self.pushButton_142.setText(_translate("DockWidget", "甘"))
        self.pushButton_143.setText(_translate("DockWidget", "川"))
        self.pushButton_144.setText(_translate("DockWidget", "滇"))
        self.pushButton_145.setText(_translate("DockWidget", "黔"))
        self.pushButton_146.setText(_translate("DockWidget", "藏"))

