# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_no_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 200)
        Dialog.setMinimumSize(QtCore.QSize(420, 200))
        Dialog.setMaximumSize(QtCore.QSize(420, 200))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(11, 15, 398, 141))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_40 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout.addWidget(self.pushButton_40, 2, 7, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout.addWidget(self.pushButton_50, 2, 8, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout.addWidget(self.pushButton_45, 2, 9, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout.addWidget(self.pushButton_39, 2, 0, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout.addWidget(self.pushButton_55, 2, 1, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout.addWidget(self.pushButton_41, 2, 3, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout.addWidget(self.pushButton_33, 2, 4, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout.addWidget(self.pushButton_38, 2, 12, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout.addWidget(self.pushButton_51, 2, 6, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout.addWidget(self.pushButton_35, 2, 11, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout.addWidget(self.pushButton_53, 2, 2, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout.addWidget(self.pushButton_52, 2, 10, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout.addWidget(self.pushButton_43, 2, 5, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_29, 4, 8, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout.addWidget(self.pushButton_49, 4, 11, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout.addWidget(self.pushButton_46, 4, 12, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_32, 4, 10, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_31, 4, 13, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout.addWidget(self.pushButton_44, 4, 4, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout.addWidget(self.pushButton_47, 4, 9, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_30, 4, 2, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout.addWidget(self.pushButton_37, 4, 1, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout.addWidget(self.pushButton_54, 4, 5, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout.addWidget(self.pushButton_36, 4, 3, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout.addWidget(self.pushButton_56, 4, 6, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout.addWidget(self.pushButton_48, 4, 7, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout.addWidget(self.pushButton_42, 4, 0, 1, 1)
        self.pushButton_59 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_59.setObjectName("pushButton_59")
        self.gridLayout.addWidget(self.pushButton_59, 5, 1, 1, 1)
        self.pushButton_70 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_70.setFont(font)
        self.pushButton_70.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_70.setObjectName("pushButton_70")
        self.gridLayout.addWidget(self.pushButton_70, 5, 0, 1, 1)
        self.pushButton_68 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_68.setFont(font)
        self.pushButton_68.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_68.setObjectName("pushButton_68")
        self.gridLayout.addWidget(self.pushButton_68, 5, 3, 1, 1)
        self.pushButton_64 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_64.setFont(font)
        self.pushButton_64.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_64.setObjectName("pushButton_64")
        self.gridLayout.addWidget(self.pushButton_64, 5, 4, 1, 1)
        self.pushButton_66 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_66.setFont(font)
        self.pushButton_66.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_66.setObjectName("pushButton_66")
        self.gridLayout.addWidget(self.pushButton_66, 5, 2, 1, 1)
        self.pushButton_75 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_75.setFont(font)
        self.pushButton_75.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_75.setObjectName("pushButton_75")
        self.gridLayout.addWidget(self.pushButton_75, 5, 5, 1, 1)
        self.pushButton_83 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_83.setFont(font)
        self.pushButton_83.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_83.setObjectName("pushButton_83")
        self.gridLayout.addWidget(self.pushButton_83, 5, 6, 1, 1)
        self.pushButton_76 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_76.setFont(font)
        self.pushButton_76.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_76.setObjectName("pushButton_76")
        self.gridLayout.addWidget(self.pushButton_76, 5, 7, 1, 1)
        self.pushButton_74 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_74.setFont(font)
        self.pushButton_74.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_74.setObjectName("pushButton_74")
        self.gridLayout.addWidget(self.pushButton_74, 5, 10, 1, 1)
        self.pushButton_69 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_69.setFont(font)
        self.pushButton_69.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_69.setObjectName("pushButton_69")
        self.gridLayout.addWidget(self.pushButton_69, 5, 11, 1, 1)
        self.pushButton_65 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_65.setFont(font)
        self.pushButton_65.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_65.setObjectName("pushButton_65")
        self.gridLayout.addWidget(self.pushButton_65, 5, 8, 1, 1)
        self.pushButton_58 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout.addWidget(self.pushButton_58, 5, 9, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 1, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 6, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 0, 12, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 0, 13, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 1, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 0, 11, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 1, 4, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_27, 1, 5, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 1, 6, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 7, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 1, 7, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 9, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 5, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 10, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 8, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 1, 12, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 1, 13, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_28, 1, 8, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 1, 10, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 1, 9, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 1, 11, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 6, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(11, 165, 401, 28))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_84 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_84.setFont(font)
        self.pushButton_84.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_84.setObjectName("pushButton_84")
        self.horizontalLayout.addWidget(self.pushButton_84)
        self.pushButton_79 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_79.setFont(font)
        self.pushButton_79.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_79.setObjectName("pushButton_79")
        self.horizontalLayout.addWidget(self.pushButton_79)
        self.pushButton_63 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_63.setFont(font)
        self.pushButton_63.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_63.setObjectName("pushButton_63")
        self.horizontalLayout.addWidget(self.pushButton_63)
        self.pushButton_61 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_61.setObjectName("pushButton_61")
        self.horizontalLayout.addWidget(self.pushButton_61)
        self.pushButton_60 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_60.setObjectName("pushButton_60")
        self.horizontalLayout.addWidget(self.pushButton_60)
        self.pushButton_71 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_71.setFont(font)
        self.pushButton_71.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_71.setObjectName("pushButton_71")
        self.horizontalLayout.addWidget(self.pushButton_71)
        self.pushButton_57 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_57.setObjectName("pushButton_57")
        self.horizontalLayout.addWidget(self.pushButton_57)
        self.pushButton_72 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_72.setFont(font)
        self.pushButton_72.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_72.setObjectName("pushButton_72")
        self.horizontalLayout.addWidget(self.pushButton_72)
        self.pushButton_77 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_77.setFont(font)
        self.pushButton_77.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_77.setObjectName("pushButton_77")
        self.horizontalLayout.addWidget(self.pushButton_77)
        self.pushButton_82 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_82.setFont(font)
        self.pushButton_82.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_82.setObjectName("pushButton_82")
        self.horizontalLayout.addWidget(self.pushButton_82)
        self.pushButton_73 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_73.setFont(font)
        self.pushButton_73.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_73.setObjectName("pushButton_73")
        self.horizontalLayout.addWidget(self.pushButton_73)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_78 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_78.setFont(font)
        self.pushButton_78.setStyleSheet("QPushButton:hover{background-color:#dadada;}\n"
"QPushButton{border:0px}")
        self.pushButton_78.setObjectName("pushButton_78")
        self.horizontalLayout.addWidget(self.pushButton_78)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(6, 1)
        self.horizontalLayout.setStretch(7, 1)
        self.horizontalLayout.setStretch(8, 1)
        self.horizontalLayout.setStretch(9, 1)
        self.horizontalLayout.setStretch(10, 1)
        self.horizontalLayout.setStretch(11, 1)
        self.horizontalLayout.setStretch(12, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "车号"))
        self.pushButton_40.setText(_translate("Dialog", "戊"))
        self.pushButton_50.setText(_translate("Dialog", "己"))
        self.pushButton_45.setText(_translate("Dialog", "庚"))
        self.pushButton_39.setText(_translate("Dialog", "青"))
        self.pushButton_55.setText(_translate("Dialog", "宁"))
        self.pushButton_41.setText(_translate("Dialog", "甲"))
        self.pushButton_33.setText(_translate("Dialog", "乙"))
        self.pushButton_38.setText(_translate("Dialog", "癸"))
        self.pushButton_51.setText(_translate("Dialog", "丁"))
        self.pushButton_35.setText(_translate("Dialog", "壬"))
        self.pushButton_53.setText(_translate("Dialog", "新"))
        self.pushButton_52.setText(_translate("Dialog", "辛"))
        self.pushButton_43.setText(_translate("Dialog", "丙"))
        self.pushButton_29.setText(_translate("Dialog", "I"))
        self.pushButton_49.setText(_translate("Dialog", "L"))
        self.pushButton_46.setText(_translate("Dialog", "M"))
        self.pushButton_32.setText(_translate("Dialog", "K"))
        self.pushButton_31.setText(_translate("Dialog", "N"))
        self.pushButton_44.setText(_translate("Dialog", "E"))
        self.pushButton_47.setText(_translate("Dialog", "J"))
        self.pushButton_30.setText(_translate("Dialog", "C"))
        self.pushButton_37.setText(_translate("Dialog", "B"))
        self.pushButton_54.setText(_translate("Dialog", "F"))
        self.pushButton_36.setText(_translate("Dialog", "D"))
        self.pushButton_56.setText(_translate("Dialog", "G"))
        self.pushButton_48.setText(_translate("Dialog", "H"))
        self.pushButton_42.setText(_translate("Dialog", "A"))
        self.pushButton_59.setText(_translate("Dialog", "P"))
        self.pushButton_70.setText(_translate("Dialog", "O"))
        self.pushButton_68.setText(_translate("Dialog", "R"))
        self.pushButton_64.setText(_translate("Dialog", "S"))
        self.pushButton_66.setText(_translate("Dialog", "Q"))
        self.pushButton_75.setText(_translate("Dialog", "T"))
        self.pushButton_83.setText(_translate("Dialog", "U"))
        self.pushButton_76.setText(_translate("Dialog", "V"))
        self.pushButton_74.setText(_translate("Dialog", "Y"))
        self.pushButton_69.setText(_translate("Dialog", "Z"))
        self.pushButton_65.setText(_translate("Dialog", "W"))
        self.pushButton_58.setText(_translate("Dialog", "X"))
        self.pushButton.setText(_translate("Dialog", "京"))
        self.pushButton_5.setText(_translate("Dialog", "蒙"))
        self.pushButton_24.setText(_translate("Dialog", "湘"))
        self.pushButton_7.setText(_translate("Dialog", "吉"))
        self.pushButton_13.setText(_translate("Dialog", "闽"))
        self.pushButton_14.setText(_translate("Dialog", "赣"))
        self.pushButton_16.setText(_translate("Dialog", "豫"))
        self.pushButton_12.setText(_translate("Dialog", "皖"))
        self.pushButton_20.setText(_translate("Dialog", "鄂"))
        self.pushButton_4.setText(_translate("Dialog", "晋"))
        self.pushButton_25.setText(_translate("Dialog", "粤"))
        self.pushButton_27.setText(_translate("Dialog", "桂"))
        self.pushButton_17.setText(_translate("Dialog", "琼"))
        self.pushButton_22.setText(_translate("Dialog", "鲁"))
        self.pushButton_8.setText(_translate("Dialog", "黑"))
        self.pushButton_23.setText(_translate("Dialog", "渝"))
        self.pushButton_3.setText(_translate("Dialog", "冀"))
        self.pushButton_10.setText(_translate("Dialog", "苏"))
        self.pushButton_6.setText(_translate("Dialog", "辽"))
        self.pushButton_11.setText(_translate("Dialog", "浙"))
        self.pushButton_9.setText(_translate("Dialog", "沪"))
        self.pushButton_2.setText(_translate("Dialog", "津"))
        self.pushButton_21.setText(_translate("Dialog", "陕"))
        self.pushButton_15.setText(_translate("Dialog", "甘"))
        self.pushButton_28.setText(_translate("Dialog", "川"))
        self.pushButton_19.setText(_translate("Dialog", "滇"))
        self.pushButton_18.setText(_translate("Dialog", "黔"))
        self.pushButton_26.setText(_translate("Dialog", "藏"))
        self.pushButton_84.setText(_translate("Dialog", "0"))
        self.pushButton_79.setText(_translate("Dialog", "1"))
        self.pushButton_63.setText(_translate("Dialog", "2"))
        self.pushButton_61.setText(_translate("Dialog", "3"))
        self.pushButton_60.setText(_translate("Dialog", "4"))
        self.pushButton_71.setText(_translate("Dialog", "5"))
        self.pushButton_57.setText(_translate("Dialog", "6"))
        self.pushButton_72.setText(_translate("Dialog", "7"))
        self.pushButton_77.setText(_translate("Dialog", "8"))
        self.pushButton_82.setText(_translate("Dialog", "9"))
        self.pushButton_73.setText(_translate("Dialog", "-"))
        self.pushButton_78.setText(_translate("Dialog", "确定"))


class ParamsDialog(QtWidgets.QDialog, Ui_Dialog):
    """
    参数修改
    """
    def __init__(self):
        super(ParamsDialog, self).__init__()
        self.setupUi(self)
        self.setWindowFlags(Qt.FramelessWindowHint)


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myshow = ParamsDialog()
    myshow.show()
    sys.exit(app.exec_())