# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cargo_manage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cargo_ManageForm(object):
    def setupUi(self, cargo_ManageForm):
        cargo_ManageForm.setObjectName("cargo_ManageForm")
        cargo_ManageForm.resize(728, 358)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(cargo_ManageForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(cargo_ManageForm)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.groupBox = QtWidgets.QGroupBox(cargo_ManageForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.CargoNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.CargoNameLineEdit.setMaxLength(15)
        self.CargoNameLineEdit.setObjectName("CargoNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CargoNameLineEdit)
        self.CargoIdLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.CargoIdLineEdit.setEnabled(True)
        self.CargoIdLineEdit.setMaxLength(15)
        self.CargoIdLineEdit.setReadOnly(True)
        self.CargoIdLineEdit.setObjectName("CargoIdLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.CargoIdLineEdit)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.CargopriceLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.CargopriceLineEdit.setMaxLength(15)
        self.CargopriceLineEdit.setObjectName("CargopriceLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CargopriceLineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.deletePushButton = QtWidgets.QPushButton(cargo_ManageForm)
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout_3.addWidget(self.deletePushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.updatePushButton = QtWidgets.QPushButton(cargo_ManageForm)
        self.updatePushButton.setObjectName("updatePushButton")
        self.horizontalLayout_3.addWidget(self.updatePushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.savePushButton = QtWidgets.QPushButton(cargo_ManageForm)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_3.addWidget(self.savePushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.cancelPushButton = QtWidgets.QPushButton(cargo_ManageForm)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.clearPushButton = QtWidgets.QPushButton(cargo_ManageForm)
        self.clearPushButton.setObjectName("clearPushButton")
        self.horizontalLayout_3.addWidget(self.clearPushButton)
        self.horizontalLayout_3.setStretch(0, 6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(cargo_ManageForm)
        QtCore.QMetaObject.connectSlotsByName(cargo_ManageForm)

    def retranslateUi(self, cargo_ManageForm):
        _translate = QtCore.QCoreApplication.translate
        cargo_ManageForm.setWindowTitle(_translate("cargo_ManageForm", "货物信息管理"))
        self.groupBox.setTitle(_translate("cargo_ManageForm", "货物管理"))
        self.label_5.setText(_translate("cargo_ManageForm", "货物名称："))
        self.label_6.setText(_translate("cargo_ManageForm", "序      号："))
        self.label_8.setText(_translate("cargo_ManageForm", "单      价："))
        self.deletePushButton.setText(_translate("cargo_ManageForm", "删除"))
        self.updatePushButton.setText(_translate("cargo_ManageForm", "修改"))
        self.savePushButton.setText(_translate("cargo_ManageForm", "保存"))
        self.cancelPushButton.setText(_translate("cargo_ManageForm", "取消"))
        self.clearPushButton.setText(_translate("cargo_ManageForm", "清除"))

