# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'permission_setup.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_permissionSetupForm(object):
    def setupUi(self, permissionSetupForm):
        permissionSetupForm.setObjectName("permissionSetupForm")
        permissionSetupForm.resize(519, 506)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(permissionSetupForm)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.userRoleQTabWidget = QtWidgets.QTabWidget(permissionSetupForm)
        self.userRoleQTabWidget.setObjectName("userRoleQTabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userListWidget = QtWidgets.QListWidget(self.tab_3)
        self.userListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.userListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.userListWidget.setObjectName("userListWidget")
        self.verticalLayout_2.addWidget(self.userListWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addUserPushButton = QtWidgets.QPushButton(self.tab_3)
        self.addUserPushButton.setObjectName("addUserPushButton")
        self.horizontalLayout_2.addWidget(self.addUserPushButton)
        self.editUserPushButton = QtWidgets.QPushButton(self.tab_3)
        self.editUserPushButton.setObjectName("editUserPushButton")
        self.horizontalLayout_2.addWidget(self.editUserPushButton)
        self.deleteUserPushButton = QtWidgets.QPushButton(self.tab_3)
        self.deleteUserPushButton.setObjectName("deleteUserPushButton")
        self.horizontalLayout_2.addWidget(self.deleteUserPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.userRoleQTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.roleListWidget = QtWidgets.QListWidget(self.tab_4)
        self.roleListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.roleListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.roleListWidget.setObjectName("roleListWidget")
        self.verticalLayout.addWidget(self.roleListWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addRolePushButton = QtWidgets.QPushButton(self.tab_4)
        self.addRolePushButton.setObjectName("addRolePushButton")
        self.horizontalLayout.addWidget(self.addRolePushButton)
        self.editRolePushButton = QtWidgets.QPushButton(self.tab_4)
        self.editRolePushButton.setObjectName("editRolePushButton")
        self.horizontalLayout.addWidget(self.editRolePushButton)
        self.deleteRolePushButton = QtWidgets.QPushButton(self.tab_4)
        self.deleteRolePushButton.setObjectName("deleteRolePushButton")
        self.horizontalLayout.addWidget(self.deleteRolePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.userRoleQTabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_3.addWidget(self.userRoleQTabWidget)
        self.permissionTabWidget = QtWidgets.QTabWidget(permissionSetupForm)
        self.permissionTabWidget.setObjectName("permissionTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.optionTableView = QtWidgets.QTableView(self.tab)
        self.optionTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.optionTableView.setAlternatingRowColors(True)
        self.optionTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.optionTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.optionTableView.setObjectName("optionTableView")
        self.verticalLayout_3.addWidget(self.optionTableView)
        self.permissionTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.permissionTableView = QtWidgets.QTableView(self.tab_2)
        self.permissionTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.permissionTableView.setAlternatingRowColors(True)
        self.permissionTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.permissionTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.permissionTableView.setObjectName("permissionTableView")
        self.verticalLayout_4.addWidget(self.permissionTableView)
        self.permissionTabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.permissionTabWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.savePushButton = QtWidgets.QPushButton(permissionSetupForm)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_4.addWidget(self.savePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(permissionSetupForm)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_4.addWidget(self.cancelPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)

        self.retranslateUi(permissionSetupForm)
        self.userRoleQTabWidget.setCurrentIndex(0)
        self.permissionTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(permissionSetupForm)

    def retranslateUi(self, permissionSetupForm):
        _translate = QtCore.QCoreApplication.translate
        permissionSetupForm.setWindowTitle(_translate("permissionSetupForm", "用户和权限管理"))
        self.addUserPushButton.setText(_translate("permissionSetupForm", "添加"))
        self.editUserPushButton.setText(_translate("permissionSetupForm", "修改"))
        self.deleteUserPushButton.setText(_translate("permissionSetupForm", "删除"))
        self.userRoleQTabWidget.setTabText(self.userRoleQTabWidget.indexOf(self.tab_3), _translate("permissionSetupForm", "用户"))
        self.addRolePushButton.setText(_translate("permissionSetupForm", "添加"))
        self.editRolePushButton.setText(_translate("permissionSetupForm", "修改"))
        self.deleteRolePushButton.setText(_translate("permissionSetupForm", "删除"))
        self.userRoleQTabWidget.setTabText(self.userRoleQTabWidget.indexOf(self.tab_4), _translate("permissionSetupForm", "角色"))
        self.permissionTabWidget.setTabText(self.permissionTabWidget.indexOf(self.tab), _translate("permissionSetupForm", "功能设置"))
        self.permissionTabWidget.setTabText(self.permissionTabWidget.indexOf(self.tab_2), _translate("permissionSetupForm", "权限设置"))
        self.savePushButton.setText(_translate("permissionSetupForm", "保存"))
        self.cancelPushButton.setText(_translate("permissionSetupForm", "取消"))

