# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receiver_manage.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_receiverManageForm(object):
    def setupUi(self, receiverManageForm):
        receiverManageForm.setObjectName("Form")
        receiverManageForm.resize(757, 488)
        self.groupBox = QtWidgets.QGroupBox(receiverManageForm)
        self.groupBox.setGeometry(QtCore.QRect(100, 250, 512, 151))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ReceiverNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ReceiverNameLineEdit.setMaxLength(15)
        self.ReceiverNameLineEdit.setObjectName("ReceiverNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ReceiverNameLineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.ReceiverPhoneLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ReceiverPhoneLineEdit.setObjectName("ReceiverPhoneLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ReceiverPhoneLineEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.ReceiverBankLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ReceiverBankLineEdit.setObjectName("ReceiverBankLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ReceiverBankLineEdit)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.ReceiverDutyLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ReceiverDutyLineEdit.setObjectName("ReceiverDutyLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ReceiverDutyLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.ReceiverContactLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ReceiverContactLineEdit.setMaxLength(15)
        self.ReceiverContactLineEdit.setObjectName("ReceiverContactLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ReceiverContactLineEdit)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.ReceiverAddressLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ReceiverAddressLineEdit.setObjectName("ReceiverAddressLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ReceiverAddressLineEdit)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.ReceiverCountLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ReceiverCountLineEdit.setObjectName("ReceiverCountLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ReceiverCountLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget = QtWidgets.QWidget(receiverManageForm)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 420, 491, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.savePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_3.addWidget(self.savePushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cancelPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.horizontalLayout_3.setStretch(0, 6)
        self.tableView = QtWidgets.QTableView(receiverManageForm)
        self.tableView.setStyleSheet("QTableView QHeaderView::section { background-color:#dadada}")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setGeometry(QtCore.QRect(100, 50, 531, 192))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(receiverManageForm)
        QtCore.QMetaObject.connectSlotsByName(receiverManageForm)

    def retranslateUi(self, receiverManageForm):
        _translate = QtCore.QCoreApplication.translate
        receiverManageForm.setWindowTitle(_translate("receiverManageForm", "Form"))
        self.groupBox.setTitle(_translate("receiverManageForm", "收货单位"))
        self.label_5.setText(_translate("receiverManageForm", "收货单位："))
        self.label_8.setText(_translate("receiverManageForm", "联系电话："))
        self.label_7.setText(_translate("receiverManageForm", "开  户 行："))
        self.label_12.setText(_translate("receiverManageForm", "税      号："))
        self.label_10.setText(_translate("receiverManageForm", "联系人："))
        self.label_9.setText(_translate("receiverManageForm", "地   址："))
        self.label_11.setText(_translate("receiverManageForm", "账   号："))
        self.savePushButton.setText(_translate("receiverManageForm", "保存"))
        self.cancelPushButton.setText(_translate("receiverManageForm", "取消"))

