# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'super_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_superForm(object):
    def setupUi(self, superForm):
        superForm.setObjectName("superForm")
        superForm.resize(959, 500)
        superForm.setMinimumSize(QtCore.QSize(800, 500))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(superForm)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(superForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.tableComboBox = QtWidgets.QComboBox(self.groupBox)
        self.tableComboBox.setMinimumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableComboBox.setFont(font)
        self.tableComboBox.setObjectName("tableComboBox")
        self.horizontalLayout.addWidget(self.tableComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.whereLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.whereLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.whereLineEdit.setFont(font)
        self.whereLineEdit.setObjectName("whereLineEdit")
        self.horizontalLayout_2.addWidget(self.whereLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.sortComboBox1 = QtWidgets.QComboBox(self.groupBox)
        self.sortComboBox1.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sortComboBox1.setFont(font)
        self.sortComboBox1.setObjectName("sortComboBox1")
        self.horizontalLayout_3.addWidget(self.sortComboBox1)
        self.sortComboBox2 = QtWidgets.QComboBox(self.groupBox)
        self.sortComboBox2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sortComboBox2.setFont(font)
        self.sortComboBox2.setObjectName("sortComboBox2")
        self.sortComboBox2.addItem("")
        self.sortComboBox2.addItem("")
        self.horizontalLayout_3.addWidget(self.sortComboBox2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.queryPushButton = QtWidgets.QPushButton(self.groupBox)
        self.queryPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.queryPushButton.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.queryPushButton.setFont(font)
        self.queryPushButton.setObjectName("queryPushButton")
        self.horizontalLayout_4.addWidget(self.queryPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addPushButton = QtWidgets.QPushButton(self.groupBox)
        self.addPushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addPushButton.setFont(font)
        self.addPushButton.setObjectName("addPushButton")
        self.horizontalLayout_5.addWidget(self.addPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.deletePushButton = QtWidgets.QPushButton(self.groupBox)
        self.deletePushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deletePushButton.setFont(font)
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout_5.addWidget(self.deletePushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.savePushButton = QtWidgets.QPushButton(self.groupBox)
        self.savePushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.savePushButton.setFont(font)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_5.addWidget(self.savePushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.cancelPushButton = QtWidgets.QPushButton(self.groupBox)
        self.cancelPushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancelPushButton.setFont(font)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_5.addWidget(self.cancelPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)

        self.retranslateUi(superForm)
        QtCore.QMetaObject.connectSlotsByName(superForm)

    def retranslateUi(self, superForm):
        _translate = QtCore.QCoreApplication.translate
        superForm.setWindowTitle(_translate("superForm", "超级管理界面"))
        self.groupBox.setTitle(_translate("superForm", "原始数据管理"))
        self.label.setText(_translate("superForm", "SELECT * FROM"))
        self.label_2.setText(_translate("superForm", "WHERE"))
        self.label_3.setText(_translate("superForm", "ORDER BY"))
        self.sortComboBox2.setItemText(0, _translate("superForm", "升序"))
        self.sortComboBox2.setItemText(1, _translate("superForm", "降序"))
        self.queryPushButton.setText(_translate("superForm", "查询"))
        self.addPushButton.setText(_translate("superForm", "添加"))
        self.deletePushButton.setText(_translate("superForm", "删除"))
        self.savePushButton.setText(_translate("superForm", "保存"))
        self.cancelPushButton.setText(_translate("superForm", "取消"))

