# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supply_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Supply_Dialog(object):
    def setupUi(self, Supply_Dialog):
        Supply_Dialog.setObjectName("Supply_Dialog")
        Supply_Dialog.resize(530, 200)
        Supply_Dialog.setMinimumSize(QtCore.QSize(530, 200))
        Supply_Dialog.setMaximumSize(QtCore.QSize(530, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Supply_Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Supply_Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.SupplyNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyNameLineEdit.setMaxLength(15)
        self.SupplyNameLineEdit.setObjectName("SupplyNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SupplyNameLineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.SupplyPhoneLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyPhoneLineEdit.setObjectName("SupplyPhoneLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.SupplyPhoneLineEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.SupplyBankLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyBankLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SupplyBankLineEdit.setObjectName("SupplyBankLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SupplyBankLineEdit)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.SupplyDutyLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyDutyLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SupplyDutyLineEdit.setObjectName("SupplyDutyLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SupplyDutyLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.SupplyContactLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyContactLineEdit.setMaxLength(15)
        self.SupplyContactLineEdit.setObjectName("SupplyContactLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SupplyContactLineEdit)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.SupplyAddressLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyAddressLineEdit.setObjectName("SupplyAddressLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.SupplyAddressLineEdit)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.SupplyCountLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyCountLineEdit.setObjectName("SupplyCountLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SupplyCountLineEdit)
        self.SupplyIdLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.SupplyIdLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SupplyIdLineEdit.setDragEnabled(True)
        self.SupplyIdLineEdit.setReadOnly(True)
        self.SupplyIdLineEdit.setPlaceholderText("")
        self.SupplyIdLineEdit.setClearButtonEnabled(False)
        self.SupplyIdLineEdit.setObjectName("SupplyIdLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SupplyIdLineEdit)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.deletePushButton = QtWidgets.QPushButton(Supply_Dialog)
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout_3.addWidget(self.deletePushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.savePushButton = QtWidgets.QPushButton(Supply_Dialog)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_3.addWidget(self.savePushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cancelPushButton = QtWidgets.QPushButton(Supply_Dialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.horizontalLayout_3.setStretch(0, 6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Supply_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Supply_Dialog)

    def retranslateUi(self, Supply_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Supply_Dialog.setWindowTitle(_translate("Supply_Dialog", "收货单位"))
        self.groupBox.setTitle(_translate("Supply_Dialog", "供货单位"))
        self.label_5.setText(_translate("Supply_Dialog", "供货单位："))
        self.label_8.setText(_translate("Supply_Dialog", "联系电话："))
        self.label_7.setText(_translate("Supply_Dialog", "开  户 行："))
        self.label_12.setText(_translate("Supply_Dialog", "税      号："))
        self.label_10.setText(_translate("Supply_Dialog", "联 系  人："))
        self.label_9.setText(_translate("Supply_Dialog", "地      址："))
        self.label_11.setText(_translate("Supply_Dialog", "账      号："))
        self.label_13.setText(_translate("Supply_Dialog", "单位序号："))
        self.deletePushButton.setText(_translate("Supply_Dialog", "删除"))
        self.savePushButton.setText(_translate("Supply_Dialog", "保存"))
        self.cancelPushButton.setText(_translate("Supply_Dialog", "取消"))

