# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_params_setup.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_systemParamsSetupForm(object):
    def setupUi(self, systemParamsSetupForm):
        systemParamsSetupForm.setObjectName("systemParamsSetupForm")
        systemParamsSetupForm.resize(515, 240)
        systemParamsSetupForm.setMinimumSize(QtCore.QSize(515, 240))
        systemParamsSetupForm.setMaximumSize(QtCore.QSize(515, 240))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(systemParamsSetupForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(systemParamsSetupForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.companyLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.companyLineEdit.setObjectName("companyLineEdit")
        self.gridLayout.addWidget(self.companyLineEdit, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 8)
        self.gridLayout.setColumnStretch(3, 16)
        self.verticalLayout.addLayout(self.gridLayout)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.priceDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.priceDoubleSpinBox.setMaximum(100000.0)
        self.priceDoubleSpinBox.setObjectName("priceDoubleSpinBox")
        self.gridLayout_2.addWidget(self.priceDoubleSpinBox, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.roundComboBox = QtWidgets.QComboBox(self.groupBox)
        self.roundComboBox.setEditable(True)
        self.roundComboBox.setObjectName("roundComboBox")
        self.roundComboBox.addItem("")
        self.roundComboBox.addItem("")
        self.roundComboBox.addItem("")
        self.gridLayout_2.addWidget(self.roundComboBox, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 5)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 8)
        self.gridLayout_2.setColumnStretch(3, 16)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.savePushButton = QtWidgets.QPushButton(self.groupBox)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout.addWidget(self.savePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(self.groupBox)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(systemParamsSetupForm)
        QtCore.QMetaObject.connectSlotsByName(systemParamsSetupForm)

    def retranslateUi(self, systemParamsSetupForm):
        _translate = QtCore.QCoreApplication.translate
        systemParamsSetupForm.setWindowTitle(_translate("systemParamsSetupForm", "系统参数设置"))
        self.groupBox.setTitle(_translate("systemParamsSetupForm", "系统参数设置"))
        self.label_12.setText(_translate("systemParamsSetupForm", "单位设置"))
        self.label_13.setText(_translate("systemParamsSetupForm", "企业名称"))
        self.comboBox.setItemText(0, _translate("systemParamsSetupForm", "千克"))
        self.comboBox.setItemText(1, _translate("systemParamsSetupForm", "吨"))
        self.checkBox.setText(_translate("systemParamsSetupForm", "是否将首页手工输入的参数（供货单位、收货单位、货物名称等）\n"
"信息自动添加到数据库"))
        self.label_14.setText(_translate("systemParamsSetupForm", "单价（元）"))
        self.label_15.setText(_translate("systemParamsSetupForm", "四舍五入"))
        self.roundComboBox.setItemText(0, _translate("systemParamsSetupForm", "元"))
        self.roundComboBox.setItemText(1, _translate("systemParamsSetupForm", "毛"))
        self.roundComboBox.setItemText(2, _translate("systemParamsSetupForm", "不四舍五入"))
        self.savePushButton.setText(_translate("systemParamsSetupForm", "保存设置"))
        self.cancelPushButton.setText(_translate("systemParamsSetupForm", "取消"))

